apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  selector:
    app: eslam
  ports:
    - port: 8080  #cluster IP service port
      targetPort: 80  # pod / container port
      nodePort: 30005  # Any port between 30000 and 32767  